# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AHS20' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AHS20
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'SDWebImage'
  pod "youtube-ios-player-helper", "~> 1.0.2"
  pod 'GoogleSignIn'

  target 'AHS20Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AHS20UITests' do
    # Pods for testing
  end

end
